services:
  - type: web
    name: spanish-translator
    env: python
    region: ohio  # Choose a region close to your users
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8001
